### ISSUE TITLE
Unable to download Netbox Slurp'it addin (Docker + Behind corp firewall)

### ISSUE THREAD

**Issue by william102281** [SaaShup/netbox-docker-plugin#192]
I am new to Linux and I have given a task to setup Netbox inside docker and would like to use Slurp'it addin for auto detect IPAM solution.

I managed to installed Netbox inside docker but I am stuck on installing the addin.

This is the steps I follow:

![image](https://github.com/user-attachments/assets/209a921e-bc2a-407c-b887-6cf7d96502d7)

![image](https://github.com/user-attachments/assets/f5c83823-0aff-44cf-ad26-f7d685e3a082)
This is what I put in: 
![image](https://github.com/user-attachments/assets/29472339-a466-4658-b4d1-0ac1187fba3d)

![image](https://github.com/user-attachments/assets/2e48c527-1e75-4b5e-85e4-7cf4e4755292)
This is what I put in: 
![image](https://github.com/user-attachments/assets/c67bdeca-e16e-4d50-91d4-b8b1cba8ad28)

![image](https://github.com/user-attachments/assets/9d5c9cc6-484a-4c9c-be86-5436bb43fc24)
This is what I put in: 
![image](https://github.com/user-attachments/assets/3a2b3d1f-487d-49f5-a0f3-8991d6fd928c)

![image](https://github.com/user-attachments/assets/d6dca4b9-f107-48da-ae0b-e07e07eea496)
This is what I put in: 
![image](https://github.com/user-attachments/assets/b8181be1-342a-409c-9a14-0ec104866c50)

So when I use the follow command to build them:
Docker compose build --no-cache
docker compose up -d

It will stuck on load metadata for docker.io/netboxcommunity/netbox:latest 
Then I run the command for the proxy
export http_proxy=http://IP:Port
export https_proxy=http://IP:Port
It will carry on until uv pip install and it will time out after around 2 minutes.
![image](https://github.com/user-attachments/assets/6f5ba304-4ac9-40d9-be8a-8a2e93e5b1f9)

I have tried to specify proxy on the Dockerfile-Plugins and add the proxy on the .env file but none of them fix it.
Any one have any ideas what I have done wrong?

Thanks

**Comment by fanshan** [comment]
Hello @william102281 

Can you try to build your image with your proxy config passed as build argument like that (see: https://docs.docker.com/reference/compose-file/build/#args)

```
services:
  netbox:
    image: netbox:latest-plugins
    pull_policy: never
    ports:
      - 8000:8080
    build:
      context: .
      dockerfile: Dockerfile-Plugins
      args:
        http_proxy: http://IP:Port
        https_proxy: http://IP:Port
  netbox-worker:
    image: netbox:latest-plugins
    pull_policy: never
  netbox-housekeeping:
    image: netbox:latest-plugins
    pull_policy: never
```

Depending on the Netbox documentation https://github.com/netbox-community/netbox-docker/wiki/Using-Netbox-Plugins you have to quote the activation of your plugin like this:

```python
PLUGINS = ["slurpit_netbox"] # see the double quote
```

Tell me if it's work ;-)

And if you need more help for creating your own Netbox image with specific installed plugins (like [our plugin netbox-docker-plugin](https://github.com/SaaShup/netbox-docker-plugin)) you can also take a look at the official [Netbox Docker repository](https://github.com/netbox-community/netbox-docker) :-)

Best regards
